DECLARE
  obj_hash varchar2(500):=null;
  CURSOR c1 IS SELECT * FROM DBA_OBJECTS WHERE OWNER = '<<sCHEMA>>' AND OBJECT_TYPE IN ('FUNCTION', 'PACKAGE', 'PROCEDURE');

  ct NUMBER:=100;
 BEGIN
	SELECT COUNT(*) into ct FROM DBA_OBJECTS WHERE OWNER='<<sCHEMA>>' and object_type='TABLE' AND OBJECT_NAME='OBJECT_HASH_TABLE';
	
	CASE WHEN ct = 0 THEN
		EXECUTE IMMEDIATE 'CREATE TABLE OBJECT_HASH_TABLE (OBJECT_NAME VARCHAR2(500), OBJECT_TYPE VARCHAR2(500), OBJECT_HASH VARCHAR2(500))';
	ELSE
		NULL; -- Do nothing
	END CASE;
	
	
	EXECUTE IMMEDIATE 'TRUNCATE TABLE OBJECT_HASH_TABLE';
	
	FOR rec in c1 LOOP
		select rawtohex(dbms_crypto.hash(dbms_metadata.get_ddl(rec.OBJECT_TYPE, rec.OBJECT_NAME, rec.OWNER), 2)) 
		INTO obj_hash  FROM DUAL;

		INSERT INTO OBJECT_HASH_TABLE (OBJECT_NAME, OBJECT_TYPE, OBJECT_HASH) 
		VALUES (rec.OBJECT_NAME, rec.OBJECT_TYPE, obj_hash);
		commit;
		obj_hash:=NULL;
	END LOOP;
  
END;
